### ISSUE TITLE
你好，请问能够提供下运行环境吗，我运行的时候报错了

### ISSUE THREAD

**Issue by lx236** [WILeroy/segmentation_model_by_tf#1]
(myconda) root@79aae93b06c4:/retina_unet-master# python train.py 
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    x_train, y_train = Generator('DRIVE', config)()
TypeError: __init__() missing 1 required positional argument: 'config'

**Comment by WILeroy** [comment]
不要意思，之前的代码还没修改完，现在已经完成了. 你可以再试一试.
运行时只需要满足tensorflow2即可.

**Comment by WILeroy** [comment]
solved.
